## 212p 결측치 처리

#### 1. 결측치 개념

In [ ]:
import pandas as pd
url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
t_df = pd.read_csv(url, sep='\t')
t_df.info()

# 컬럼명 모두 소문자로 바꾸기
t_df.columns = [col.lower() for col in t_df.columns]
t_df.columns

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

#### 2. 결측치 확인 함수

In [21]:
# isna
t_df['age'][t_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [20]:
# isnull
t_df['age'].isnull()
t_df['age'][t_df['age'].isnull()]
t_df['age'][t_df['age'].isnull()].isnull().sum()

np.int64(30)

In [19]:
# notnull
t_df['age'].notnull()
t_df['age'][t_df['age'].notnull()]
t_df.loc[t_df['age'].notnull(), ['age', 'name']]

# (isnull)
# t_df.loc[t_df['age'].isnull(), ['age', 'name']]

      age                                               name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
150  51.0                         Bateman, Rev. Robert James
151  22.0                  Pears, Mrs. Thomas (Edith Wearne)
152  55.5                                   Meo, Mr. Alfonzo
153  40.5                    van Billiard, Mr. Austin Blyler
155  51.0                        Williams, Mr. Charles Duane

[126 rows x 2 columns]

#### 3. 결측치 처리 방법

In [ ]:
# 결측치를 다른 문자로 변경하기
t_df.head()
t_df['cabin'] = t_df['cabin'].fillna('N')
t_df['cabin']
t_df['cabin'].value_counts()
t_df['cabin'][0]
t_df['cabin'] = t_df['cabin'].apply(lambda x : x[0])
t_df['cabin']
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        156 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [ ]:
# 결측치를 평균값으로 변경하기
t_df_copy = t_df.copy()
t_df_copy

t_df_copy['age'].isnull()

t_df_copy['age'] = t_df_copy['age'].fillna(t_df_copy['age'].mean())
t_df_copy['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

#### 220p 여기서 잠깐 (데이터프레임 복사 - 얕은 복사와 깊은 복사)

In [32]:
copy_t_df = t_df.copy()
copy_t_df

hex(id(t_df))

hex(id(copy_t_df))

t_df.head()

copy_t_df.head()

copy_t_df['age'] = 0
copy_t_df.head()

t_df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S