## 233p 판다스의 통계 함수 (주석은 앞장 데이터 변환 해야 가능)

In [20]:
import pandas as pd
url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
t_df = pd.read_csv(url, sep='\t')
t_df.columns = [col.lower() for col in t_df.columns]

#### 1. 기본 통계 함수

In [21]:
# 데이터의 통계치 확인하기
t_df.describe()

,passengerid,survived,pclass,age,sibsp,parch,fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [22]:
# 합계 구하기: sum 함수
t_df.sum()

passengerid                                                12246
survived                                                      54
pclass                                                       378
name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
sex            malefemalefemalefemalemalemalemalemalefemalefe...
age                                                      3545.83
sibsp                                                         96
parch                                                         62
ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
fare                                                   4385.0956
cabin          C85C123E46G6C103D56A6C23 C25 C27B78D33B30C52B2...
embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object

In [23]:
# 총 개수 구하기: count 함수
t_df.count()

passengerid    156
survived       156
pclass         156
name           156
sex            156
age            126
sibsp          156
parch          156
ticket         156
fare           156
cabin           31
embarked       155
dtype: int64

In [24]:
# 최댓값 구하기: max 함수
t_df.max()

passengerid                                156
survived                                     1
pclass                                       3
name           van Billiard, Mr. Austin Blyler
sex                                       male
age                                       71.0
sibsp                                        5
parch                                        5
ticket                             W.E.P. 5734
fare                                     263.0
cabin                                       G6
embarked                                     S
dtype: object

In [25]:
# 최솟값 구하기: min 함수
t_df.min()

passengerid                                                 1
survived                                                    0
pclass                                                      1
name           Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
sex                                                    female
age                                                      0.83
sibsp                                                       0
parch                                                       0
ticket                                                 110465
fare                                                     6.75
cabin                                                      A5
embarked                                                    C
dtype: object

In [27]:
# 평균값 구하기: mean 함수
# t_df.mean()

In [29]:
# 중앙값 구하기: median 함수
# t_df.median()

In [30]:
# 최빈값 구하기: mode 함수
t_df.mode()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0.0,3.0,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",male,21.0,0.0,0.0,113803,8.05,C123,S
1,2,NaN,NaN,"Allen, Mr. William Henry",NaN,NaN,NaN,NaN,11668,NaN,C23 C25 C27,NaN
2,3,NaN,NaN,"Andersson, Miss. Ellis Anna Maria",NaN,NaN,NaN,NaN,19950,NaN,D26,NaN
3,4,NaN,NaN,"Andersson, Miss. Erna Alexandra",NaN,NaN,NaN,NaN,237736,NaN,NaN,NaN
4,5,NaN,NaN,"Andersson, Mr. Anders Johan",NaN,NaN,NaN,NaN,2651,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,NaN,NaN,"Williams, Mr. Charles Duane",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,153,NaN,NaN,"Williams, Mr. Charles Eugene",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,154,NaN,NaN,"Woolner, Mr. Hugh",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,155,NaN,NaN,"Zabour, Miss. Hileni",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,156,NaN,NaN,"van Billiard, Mr. Austin Blyler",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# 편차 구하기: mad 함수
# t_df.mad()

In [34]:
# 분산 구하기: var 함수
# t_df.var()

In [36]:
# 표준편차 구하기: std 함수
# t_df.std()

In [38]:
# 왜도 구하기: skew 함수
# t_df.skew()

In [40]:
# 첨도 구하기: kurt 함수
# t_df.kurt()

#### 2. 특정 열의 통계치 구하기

In [41]:
# 최댓값 구하기
t_df['age'].max()

np.float64(71.0)

In [42]:
# 최솟값 구하기
t_df['age'].min()

np.float64(0.83)

In [43]:
# 합계 구하기
t_df['age'].sum()

np.float64(3545.83)

In [44]:
# 개수 구하기
t_df['age'].count()

np.int64(126)

In [45]:
# 평균값 구하기 1
t_df['age'].mean()

np.float64(28.141507936507935)

In [46]:
# 평균값 구하기 2
t_df['age'].sum()/t_df['age'].count()

np.float64(28.141507936507935)

In [47]:
# 표준편차 구하기
t_df['age'].std()

np.float64(14.613879926560793)

In [48]:
# 중간값 구하기
t_df['age'].median()

np.float64(26.0)

In [49]:
# 최빈값 구하기
t_df['age'].mode()

0    21.0
Name: age, dtype: float64